In [1]:
text_science = '''
        Scientists discover a new species of the marine life in deep ocean.
        The discovery is a significant advancement in marine biology are And and and.
                '''

In [2]:
text_economy = '''
        Stock markets soar as companies report record profits for the quarter.
        Investors are optimistic about the future of the economy.
                '''

In [3]:
text_sport = '''
        Team USA clinches gold in a thrilling overtime victory at the Winter Olympics,
        showcasing their determination and skill on the ice.
            '''

In [4]:
documents = [text_science,text_economy,text_sport]
labels = ['science','economy','sport']

In [5]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [6]:
vectorizer = CountVectorizer(ngram_range=(1,2),lowercase=True)
bow = vectorizer.fit_transform(documents)

In [7]:
X = bow.toarray()

In [8]:
X.shape

(3, 107)

In [9]:
X.shape

(3, 107)

In [10]:
features = vectorizer.get_feature_names_out()

In [11]:
features

array(['about', 'about the', 'advancement', 'advancement in', 'and',
       'and and', 'and skill', 'are', 'are and', 'are optimistic', 'as',
       'as companies', 'at', 'at the', 'biology', 'biology are',
       'clinches', 'clinches gold', 'companies', 'companies report',
       'deep', 'deep ocean', 'determination', 'determination and',
       'discover', 'discover new', 'discovery', 'discovery is', 'economy',
       'for', 'for the', 'future', 'future of', 'gold', 'gold in', 'ice',
       'in', 'in deep', 'in marine', 'in thrilling', 'investors',
       'investors are', 'is', 'is significant', 'life', 'life in',
       'marine', 'marine biology', 'marine life', 'markets',
       'markets soar', 'new', 'new species', 'ocean', 'ocean the', 'of',
       'of the', 'olympics', 'olympics showcasing', 'on', 'on the',
       'optimistic', 'optimistic about', 'overtime', 'overtime victory',
       'profits', 'profits for', 'quarter', 'quarter investors', 'record',
       'record profits', 'report', 'report record', 'scientists',
       'scientists discover', 'showcasing', 'showcasing their',
       'significant', 'significant advancement', 'skill', 'skill on',
       'soar', 'soar as', 'species', 'species of', 'stock',
       'stock markets', 'team', 'team usa', 'the', 'the discovery',
       'the economy', 'the future', 'the ice', 'the marine',
       'the quarter', 'the winter', 'their', 'their determination',
       'thrilling', 'thrilling overtime', 'usa', 'usa clinches',
       'victory', 'victory at', 'winter', 'winter olympics'], dtype=object)

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(X,columns=features)

In [15]:
df

,about,about the,advancement,advancement in,and,and and,and skill,are,are and,are optimistic,...,their,their determination,thrilling,thrilling overtime,usa,usa clinches,victory,victory at,winter,winter olympics
0,0,0,1,1,3,2,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,1,0,0,0,...,1,1,1,1,1,1,1,1,1,1

In [16]:
#tf-idf
#tf: term frequency
#idf : inverse document frequency

In [17]:
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(documents)

In [18]:
features = tfidf_vectorizer.get_feature_names_out()

In [19]:
df = pd.DataFrame(X_tfidf.toarray(),columns=features)

In [20]:
df

,about,advancement,and,are,as,at,biology,clinches,companies,deep,...,soar,species,stock,team,the,their,thrilling,usa,victory,winter
0,0.000000,0.195848,0.446842,0.148947,0.000000,0.000000,0.195848,0.000000,0.000000,0.195848,...,0.000000,0.195848,0.000000,0.000000,0.231342,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.227648,0.000000,0.000000,0.173132,0.227648,0.000000,0.000000,0.000000,0.227648,0.000000,...,0.227648,0.000000,0.227648,0.000000,0.403357,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.176570,0.000000,0.000000,0.232169,0.000000,0.232169,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.232169,0.274245,0.232169,0.232169,0.232169,0.232169,0.232169