In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('persian_news/train.csv',delimiter = '\t')

In [3]:
train_data

,Unnamed: 0,content,label,label_id
0,0,به گزارش خبرنگار حوزه بهداشت و درمان گروه علمی...,پزشکی,7
1,1,به گزارش خبرنگار فوتبال و فوتسال گروه ورزشی با...,ورزشی,6
2,2,بهروز اکرمی، در گفتگو با خبرنگار اجتماعی باشگا...,اجتماعی,0
3,3,به گزارش خبرنگار حوزه شهری گروه اجتماعی باشگاه...,اجتماعی,0
4,4,به گزارش باشگاه خبرنگاران و به نقل از روابط عم...,فرهنگی هنری,5
...,...,...,...,...
13309,13309,به گزارش خبرنگار دولت باشگاه خبرنگاران رضا فرج...,سیاسی,3
13310,13310,به گزارش خبرنگار اقتصادی باشگاه خبرنگاران، باز...,اقتصادی,1
13311,13311,ایسوس همیشه سورپرایزهایی را برای کامپیوتکس کنا...,علمی فناوری,4
13312,13312,به گزارش حوزه مجلس گروه سیاسی باشگاه خبرنگاران...,سیاسی,3
13313,13313,به گزارش خبرنگار اقتصادی باشگاه خبرنگاران؛ در ...,اقتصادی,1

In [4]:
category_id = train_data[['label','label_id']].drop_duplicates().set_index('label_id').to_dict()['label']

In [5]:
y_train = train_data['label_id']

In [6]:
train_data.columns

Index(['Unnamed: 0', 'content', 'label', 'label_id'], dtype='object')

In [7]:
train_data.drop(columns=['Unnamed: 0','label', 'label_id'], inplace=True)

In [8]:
print(train_data['content'][0])

به گزارش خبرنگار حوزه بهداشت و درمان گروه علمی پزشکی باشگاه خبرنگاران جوان؛ محمد آقاجانی روز دوشنبه در نشست مشترک و هم اندیشی اعضای کمیسیون برنامه، بودجه و محاسبات مجلس و شورای معاونین وزارت بهداشت، اظهار داشت: در بیش از ۶۰۰ کلینیک ویژه در سطح کشور از ابتدای طرح تحول سلامت تا پایان سال گذشته، ۱۱۰ میلیون بار ویزیت تخصصی و فوق تخصصی با دریافت بهای بسیار اندک حدود ۳ هزار تومانی برای مردم طبقات محروم و متوسط انجام شد. وی به بیان مهمترین مشکلات پیش روی طرح تحول سلامت پرداخت و گفت: مهمترین معضل این طرح، عدم پایداری منابع است و اعتبارات وزارت بهداشت در سه سال اخیر به طور کامل محقق نشد. آقاجانی تصریح کرد: در سال ۹۵ معادل یک سوم بودجه سال ۹۳، به وزارت بهداشت بودجه تخصیص یافت اما خدمات حوزه سلامت همچنان با تلاش‌ها و زحمات جامعه پزشکی، پرستاری و کادر بهداشتی و درمانی کشور، بدون هیچ گونه کاستی به مردم ارائه می‌شود. معاون درمان وزارت بهداشت تاکید کرد: برای جبران کاهش بودجه وزارت بهداشت در سال سوم اجرای طرح تحول سلامت نسبت به سال اول، در هزینه‌های به طور جدی صرفه جویی کردیم. اما سال گذشته از محل هدفمندی یارانه‌ها نیز اعتباری دریافت نکردیم. آقاجانی در خصوص وضعیت مطالبات وزارت بهداشت از بیمه‌ها، یادآور شد: بیمارستانهای وزارت بهداشت هنوز مطالبات ۷ ماه از سال گذشته را از بیمه‌ها دریافت نکرده‌اند و حدود ۹ هزار و ۵۰۰ میلیارد تومان اسناد ارسالی به بیمه‌ها دارند. وی به وجود سامانه مرکزی خدمات بستری در وزارت بهداشت اشاره کرد و افزود: بر اساس اطلاعات این سامانه، رشد خدمات بستری پس از طرح تحول سلامت، فقط ۵ درصد است در حالی که شاهد رشد ۱۱ درصدی بیمه شدگان بودیم بنابراین تقاضای القایی ایجاد نشده اما در حوزه خدمات سرپایی ممکن است تقاضای القای وجود داشته باشد چون دفترچه سفیدی را در اختیار مردم قرار می‌دهیم که ممکن است هر روز به پرشکان مختلف مراجعه کنند و چندین خدمت پزشکی را دریافت کنند.

In [9]:
text = train_data['content'][0]

In [10]:
import hazm

In [11]:
normalizer = hazm.Normalizer()
text = normalizer.normalize(text)

In [12]:
tokenizer = hazm.WordTokenizer()
tokens = tokenizer.tokenize(text)

In [13]:
import string

In [14]:
stop_word = hazm.stopwords_list()
punctuation = list(string.punctuation + '؟،؛')
stemmer = hazm.Stemmer()

In [15]:
filter_sentence = []
for token in tokens:
    if (not token.isdigit()) and (token not in stop_word) and (token not in punctuation):
        filter_sentence.append(token)

In [16]:
text = ' '.join(filter_sentence)

In [17]:
print(text)

گزارش خبرنگار حوزه بهداشت درمان گروه علمی پزشکی باشگاه خبرنگاران جوان محمد آقاجانی روز دوشنبه مشترک هم‌اندیشی اعضای کمیسیون برنامه بودجه محاسبات مجلس شورای معاونین وزارت بهداشت اظهار کلینیک سطح کشور ابتدای طرح تحول سلامت پایان سال گذشته میلیون ویزیت تخصصی تخصصی دریافت بهای اندک هزار تومانی مردم طبقات محروم متوسط انجام مهمترین مشکلات طرح تحول سلامت پرداخت مهمترین معضل طرح پایداری منابع اعتبارات وزارت بهداشت سال محقق نشد آقاجانی تصریح سال معادل بودجه سال وزارت بهداشت بودجه تخصیص خدمات حوزه سلامت تلاش‌ها زحمات جامعه پزشکی پرستاری کادر بهداشتی درمانی کشور هیچ‌گونه کاستی مردم ارائه معاون درمان وزارت بهداشت تاکید جبران کاهش بودجه وزارت بهداشت سال اجرای طرح تحول سلامت سال هزینه‌های صرفه‌جویی کردیم سال گذشته محل هدفمندی یارانه‌ها اعتباری دریافت نکردیم آقاجانی وضعیت مطالبات وزارت بهداشت بیمه‌ها یادآور بیمارستانهای وزارت بهداشت مطالبات ماه سال گذشته بیمه‌ها دریافت نکرده‌اند هزار میلیارد تومان اسناد ارسالی بیمه‌ها سامانه مرکزی خدمات بستری وزارت بهداشت اشاره اساس اطلاعات سامانه خدمات بستری طرح تحول سلامت درصد شاهد درصدی بیمه شدگان بودیم تقاضای القایی ایجاد نشده حوزه خدمات سرپایی تقاضای القای دفترچه سفیدی اختیار مردم قرار می‌دهیم روز پرشکان مختلف مراجعه چندین خدمت پزشکی دریافت

In [19]:
def text_cleaner(text):
    normalizer = hazm.Normalizer()
    text = normalizer.normalize(text)

    tokenizer = hazm.WordTokenizer()
    tokens = tokenizer.tokenize(text)
    
    stop_word = hazm.stopwords_list()
    punctuation = list(string.punctuation + '؟،؛')
    stemmer = hazm.Stemmer()

    filter_sentence = []
    for token in tokens:
        if (not token.isdigit()) and (token not in stop_word) and (token not in punctuation):
            filter_sentence.append(stemmer.stem(token))
    
    text = ' '.join(filter_sentence)
        
    return text

In [25]:
%%time
for i in range(10):
    text = train_data['content'][i]
    text_c = text_cleaner(text)

CPU times: total: 109 ms
Wall time: 4.66 s

In [22]:
print(text_c)

گزار خبرنگار حوزه بهدا در گروه علم پزشک باشگاه خبرنگار جو محمد آقاجان روز دوشنبه مشترک هم‌اندیش اعضا کمیسیون برنامه بودجه محاسب مجلس شورا معاونین وزار بهدا اظهار کلینیک سطح کشور ابتدا طرح تحول سلام پا سال گذشته میلیون ویز تخصص تخصص دریاف ب اندک هزار تومان مرد طبق محرو متوسط انجا مه مشکل طرح تحول سلام پرداخ مه معضل طرح پایدار منابع اعتبار وزار بهدا سال محقق نشد آقاجان تصریح سال معادل بودجه سال وزار بهدا بودجه تخصیص خد حوزه سلام تلاش زح جامعه پزشک پرستار کادر بهداشت درمان کشور هیچ‌گونه کاست مرد ارائه معاون در وزار بهدا تاکید جبر کاه بودجه وزار بهدا سال اجرا طرح تحول سلام سال هزینه صرفه‌جو کرد سال گذشته محل هدفمند یارانه اعتبار دریاف نکرد آقاجان وضع مطالب وزار بهدا بیمه یادآور بیمارستان وزار بهدا مطالب ماه سال گذشته بیمه دریاف نکرده‌اند هزار میلیارد تو اسناد ارسال بیمه سامانه مرکز خد بستر وزار بهدا اشاره اساس اطلاع سامانه خد بستر طرح تحول سلام درصد شاهد درصد بیمه شدگ بود تقاضا القا ایجاد نشده حوزه خد سرپا تقاضا القا دفترچه سفید اختیار مرد قرار می‌ده روز پرشک مختلف مراجعه چندین خدم پزشک دریاف

In [28]:
train_data['content'] = train_data['content'].apply(text_cleaner)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

In [34]:
vectorizer = TfidfVectorizer(min_df=2)
X_train = vectorizer.fit_transform(train_data['content'])

In [35]:
X_train.shape

(13314, 28030)

In [36]:
svm_clf = SVC()
svm_clf.fit(X_train,y_train)

SVC()

In [37]:
svm_clf.score(X_train,y_train)

0.9884332281808622

In [39]:
test_data = pd.read_csv('persian_news/test.csv',delimiter = '\t')

In [41]:
y_test = test_data['label_id']

In [42]:
test_data.drop(columns=['Unnamed: 0','label', 'label_id'], inplace=True)

In [43]:
test_data

                                                content
0     حسن جوهرچی بازیگر سینما و تلویزیون ایران در گف...
1     به گزارش گروه بین الملل باشگاه خبرنگاران جوان ...
2     به گزارش خبرنگار فوتبال و فوتسال گروه ورزشی با...
3     به‌ گزارش گروه اقتصادی باشگاه خبرنگاران به نقل...
4     به گزارش خبرنگار حوزه قرآن و عترت گروه فرهنگی ...
...                                                 ...
1639  طرح رجیستری که برای قانون‌مند شدن واردات موبای...
1640  به گزارش گروه بین‌الملل باشگاه خبرنگاران جوان ...
1641  به گزارش گروه ورزشی باشگاه خبرنگاران، مرحله یک...
1642  مجله شبانه باشگاه خبرنگاران؛ عطا کردی خطا کردم...
1643  به گزارش حوزه مجلس گروه سیاسی باشگاه خبرنگاران...

[1644 rows x 1 columns]

In [44]:
test_data['content'] = test_data['content'].apply(text_cleaner)

In [45]:
X_test = vectorizer.transform(test_data['content'])

In [46]:
svm_clf.score(X_test,y_test)

0.8972019464720195